feat(azure): customize entra and platform logs (SSPROD-43735)
sysdiglabs/terraform-azurerm-secure pull request #52
Opened 2024-08-27 15:40 UTC by SKosier

2024-08-29 09:07 UTC, legobrick requested changes
We need to make this backwards compatible, so the default setup should enable everything. We should also continue supporting enable_entra variable for the time being, for whomever has a onboarding setup generated after that was introduced

2024-08-29 09:07 UTC, legobrick commented on modules/integrations/event-hub/main.tf
> +  count = length(var.enabled_entra_logs) > 0 ? 1 : 0
```suggestion
  count = var.enable_entra && length(var.enabled_entra_logs) > 0 ? 1 : 0
```

2024-08-29 09:07 UTC, legobrick commented on modules/integrations/event-hub/variables.tf
> +  default     = []
```suggestion
  default     = ["AuditLogs","SignInLogs","NonInteractiveUserSignInLogs","ServicePrincipalSignInLogs","ManagedIdentitySignInLogs","ProvisioningLogs","ADFSSignInLogs","RiskyUsers","UserRiskEvents","NetworkAccessTrafficLogs","RiskyServicePrincipals","ServicePrincipalRiskEvents","EnrichedOffice365AuditLogs","MicrosoftGraphActivityLogs","RemoteNetworkHealthLogs"]
```

2024-09-02 09:56 UTC, legobrick requested changes
Please adapt the README to add the new variables
Also mark `enabled_entra_logs` as deprecated

2024-09-02 13:34 UTC, jacalvo approved these changes
I can confirm this is working, tested pointing to the local module on `skosier/modular-onboarding/entra-logs` branch with this:
```
  enabled_entra_logs       = ["SignInLogs","NonInteractiveUserSignInLogs","ServicePrincipalSignInLogs","ManagedIdentitySignInLogs","ProvisioningLogs","ADFSSignInLogs","RiskyUsers","UserRiskEvents","NetworkAccessTrafficLogs","RiskyServicePrincipals","ServicePrincipalRiskEvents","EnrichedOffice365AuditLogs","MicrosoftGraphActivityLogs"]
  enabled_platform_logs    = ["Administrative","Policy"]
```
And they are created as expected:
![image](https://github.com/user-attachments/assets/7557c541-26d7-4655-be44-c0f2741c9c9c)
![image](https://github.com/user-attachments/assets/3b2ff763-17b7-4c1e-88e3-94067a7d1439)

2024-09-02 14:34 UTC, legobrick requested changes

2024-09-02 14:34 UTC, legobrick commented on modules/integrations/event-hub/README.md
> +| <a name="input_enable_entra"></a> [enable\_entra](#input\_enable\_entra)                                                                 | (Deprecated) Used to enable or disable Entra logs, default
```suggestion
| <a name="input_enable_entra"></a> [enable\_entra](#input\_enable\_entra)                                                                 | (Deprecated, see [enabled_entra_logs](#input\_enabled\_entra\_logs)) Used to enable or disable Entra logs, defaults to true.                                                                             | `bool`         | `true` | no |
```

2024-09-02 14:38 UTC, legobrick approved these changes

2024-09-02 14:39 UTC, merged